// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/protobuf-project/example/other/other.proto (package other, syntax proto3)
/* eslint-disable */

import type { MessageType, PartialFieldInfo } from '@aptre/protobuf-es-lite'
import { createMessageType, Message, Timestamp } from '@aptre/protobuf-es-lite'

export const protobufPackage = 'other'

/**
 * @generated from message other.OtherMessage
 */
export type OtherMessage = Message<{
  /**
   * Timestamp is an example of a Date encoding.
   *
   * @generated from field: google.protobuf.Timestamp timestamp = 1;
   */
  timestamp?: Timestamp
}>

export const OtherMessage: MessageType<OtherMessage> = createMessageType({
  typeName: 'other.OtherMessage',
  fields: [
    { no: 1, name: 'timestamp', kind: 'message', T: () => Timestamp },
  ] as readonly PartialFieldInfo[],
  packedByDefault: true,
})
