// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/aperturerobotics/genproto/src/test.proto

package pbtest

import (
	fmt "fmt"
	other "github.com/aperturerobotics/genproto/src/other"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestMessage struct {
	OtherMessage         *other.OtherMessage `protobuf:"bytes,1,opt,name=other_message,json=otherMessage,proto3" json:"other_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TestMessage) Reset()         { *m = TestMessage{} }
func (m *TestMessage) String() string { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()    {}
func (*TestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3014d61e598b96d, []int{0}
}

func (m *TestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMessage.Unmarshal(m, b)
}
func (m *TestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMessage.Marshal(b, m, deterministic)
}
func (m *TestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMessage.Merge(m, src)
}
func (m *TestMessage) XXX_Size() int {
	return xxx_messageInfo_TestMessage.Size(m)
}
func (m *TestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TestMessage proto.InternalMessageInfo

func (m *TestMessage) GetOtherMessage() *other.OtherMessage {
	if m != nil {
		return m.OtherMessage
	}
	return nil
}

func init() {
	proto.RegisterType((*TestMessage)(nil), "pbtest.TestMessage")
}

func init() {
	proto.RegisterFile("github.com/aperturerobotics/genproto/src/test.proto", fileDescriptor_e3014d61e598b96d)
}

var fileDescriptor_e3014d61e598b96d = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4e, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x2c, 0x48, 0x2d, 0x2a, 0x29, 0x2d, 0x4a, 0x2d,
	0xca, 0x4f, 0xca, 0x2f, 0xc9, 0x4c, 0x2e, 0xd6, 0x4f, 0x4f, 0xcd, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0xd7, 0x2f, 0x2e, 0x4a, 0xd6, 0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x03, 0x73, 0x85, 0xd8, 0x0a, 0x92,
	0x40, 0x3c, 0x29, 0x2b, 0xa2, 0x35, 0xe7, 0x97, 0x64, 0xa4, 0x16, 0x41, 0x48, 0x88, 0x19, 0x4a,
	0xee, 0x5c, 0xdc, 0x21, 0xa9, 0xc5, 0x25, 0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x42, 0x16,
	0x5c, 0xbc, 0x60, 0xd9, 0xf8, 0x5c, 0x88, 0x80, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0xb0,
	0x1e, 0x44, 0x8f, 0x3f, 0x88, 0x84, 0xaa, 0x0d, 0xe2, 0xc9, 0x47, 0xe2, 0x25, 0xb1, 0x81, 0xcd,
	0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x44, 0x82, 0xbe, 0xca, 0x00, 0x00, 0x00,
}
